"""Structural protocol describing the settings surface used by the application layer.

Concrete ``Settings`` from ``config.schema`` satisfies this protocol via structural
subtyping.  Application code never imports from ``dojiwick.config`` directly; it
depends on this protocol instead.
"""

from typing import Protocol

from dojiwick.domain.enums import (
    AdaptiveMode,
    EntryPriceModel,
    MarketState,
    MissingBarPolicy,
    PositionMode,
    WFMode,
)
from dojiwick.domain.models.value_objects.cost_model import CostModel
from dojiwick.domain.models.value_objects.params import RegimeParams, RiskParams, StrategyParams
from dojiwick.domain.type_aliases import ProductCode, VenueCode


# Sub-section protocols


class RegimeSettingsPort(Protocol):
    @property
    def params(self) -> RegimeParams: ...
    @property
    def hysteresis_bars(self) -> int: ...
    @property
    def min_confidence(self) -> float: ...
    @property
    def atr_extreme_pct(self) -> float: ...


class RiskSettingsPort(Protocol):
    @property
    def params(self) -> RiskParams: ...
    @property
    def risk_per_trade_pct(self) -> float: ...
    @property
    def max_consecutive_losses(self) -> int: ...
    @property
    def max_daily_loss_pct(self) -> float: ...
    @property
    def max_open_positions(self) -> int: ...
    @property
    def min_rr_ratio(self) -> float: ...
    @property
    def min_notional_usd(self) -> float: ...
    @property
    def max_notional_pct_of_equity(self) -> float: ...
    @property
    def max_notional_usd(self) -> float: ...
    @property
    def max_loss_per_trade_pct(self) -> float: ...
    @property
    def max_portfolio_risk_pct(self) -> float: ...
    @property
    def trade_cooldown_sec(self) -> int: ...
    @property
    def pair_win_rate_floor(self) -> float: ...
    @property
    def max_sector_exposure(self) -> int: ...
    @property
    def max_risk_inflation_mult(self) -> float: ...
    @property
    def drawdown_halt_pct(self) -> float: ...
    @property
    def drawdown_risk_scale_enabled(self) -> bool: ...
    @property
    def drawdown_risk_scale_max_dd(self) -> float: ...
    @property
    def drawdown_risk_scale_floor(self) -> float: ...
    @property
    def equity_curve_filter_enabled(self) -> bool: ...
    @property
    def equity_curve_filter_period(self) -> int: ...
    @property
    def portfolio_risk_baseline_pairs(self) -> int: ...
    # Rule config (for build_default_risk_engine)
    @property
    def daily_loss_precedence(self) -> int: ...
    @property
    def daily_loss_severity(self) -> float: ...
    @property
    def max_positions_precedence(self) -> int: ...
    @property
    def max_positions_severity(self) -> float: ...
    @property
    def zero_stop_precedence(self) -> int: ...
    @property
    def zero_stop_severity(self) -> float: ...
    @property
    def min_rr_precedence(self) -> int: ...
    @property
    def min_rr_severity(self) -> float: ...


class AISettingsPort(Protocol):
    @property
    def enabled(self) -> bool: ...
    @property
    def veto_enabled(self) -> bool: ...
    @property
    def fail_open_on_error(self) -> bool: ...
    @property
    def regime_enabled(self) -> bool: ...
    @property
    def regime_fail_open_on_error(self) -> bool: ...
    @property
    def regime_agreement_boost(self) -> float: ...
    @property
    def regime_disagreement_penalty(self) -> float: ...
    @property
    def daily_budget_usd(self) -> float: ...


class FlagsPort(Protocol):
    @property
    def halted_pairs(self) -> tuple[str, ...]: ...
    @property
    def exits_only_mode(self) -> bool: ...
    @property
    def ai_veto_shadow_mode(self) -> bool: ...
    @property
    def ai_regime_shadow_mode(self) -> bool: ...
    @property
    def global_halt(self) -> bool: ...
    @property
    def disable_llm(self) -> bool: ...


class TradingSettingsPort(Protocol):
    @property
    def primary_pair(self) -> str: ...
    @property
    def active_pairs(self) -> tuple[str, ...]: ...
    @property
    def enabled_strategies(self) -> tuple[str, ...] | None: ...
    @property
    def candle_interval(self) -> str: ...
    @property
    def candle_lookback(self) -> int: ...
    @property
    def rsi_period(self) -> int: ...
    @property
    def ema_fast_period(self) -> int: ...
    @property
    def ema_slow_period(self) -> int: ...
    @property
    def ema_base_period(self) -> int: ...
    @property
    def ema_trend_period(self) -> int: ...
    @property
    def atr_period(self) -> int: ...
    @property
    def adx_period(self) -> int: ...
    @property
    def bb_period(self) -> int: ...
    @property
    def bb_std(self) -> float: ...
    @property
    def volume_ema_period(self) -> int: ...


class BacktestSettingsPort(Protocol):
    @property
    def cost_model(self) -> CostModel: ...
    @property
    def equity_usd(self) -> float: ...
    @property
    def warmup_bars(self) -> int: ...
    @property
    def entry_price_model(self) -> EntryPriceModel: ...
    @property
    def partial_fill_enabled(self) -> bool: ...
    @property
    def partial_fill_threshold_pct(self) -> float: ...
    @property
    def partial_fill_min_ratio(self) -> float: ...
    @property
    def fee_bps(self) -> float: ...
    @property
    def slippage_bps(self) -> float: ...
    @property
    def leverage(self) -> float: ...
    @property
    def fee_multiplier(self) -> float: ...
    @property
    def funding_rate_per_bar(self) -> float: ...
    @property
    def impact_bps(self) -> float: ...
    @property
    def max_volume_pct(self) -> float: ...


class ExchangeSettingsPort(Protocol):
    @property
    def venue(self) -> VenueCode: ...
    @property
    def product(self) -> ProductCode: ...
    @property
    def position_mode(self) -> PositionMode: ...
    @property
    def api_key_env(self) -> str: ...
    @property
    def api_secret_env(self) -> str: ...
    @property
    def testnet(self) -> bool: ...
    @property
    def recv_window_ms(self) -> int: ...
    @property
    def connect_timeout_sec(self) -> float: ...
    @property
    def read_timeout_sec(self) -> float: ...
    @property
    def retry_max_attempts(self) -> int: ...
    @property
    def retry_base_delay_sec(self) -> float: ...
    @property
    def backoff_factor(self) -> float: ...
    @property
    def rate_limit_per_sec(self) -> int: ...


class UniverseSettingsPort(Protocol):
    @property
    def account(self) -> str: ...
    @property
    def quote_asset(self) -> str: ...
    @property
    def settle_asset(self) -> str: ...
    @property
    def pair_separator(self) -> str: ...
    @property
    def symbol_separator(self) -> str: ...


class SystemSettingsPort(Protocol):
    @property
    def tick_interval_sec(self) -> int: ...
    @property
    def log_level(self) -> str: ...
    @property
    def shutdown_timeout_sec(self) -> int: ...
    @property
    def max_ticks(self) -> int: ...
    @property
    def max_consecutive_errors(self) -> int: ...
    @property
    def missing_bar_policy(self) -> MissingBarPolicy: ...
    @property
    def reconciliation_interval_ticks(self) -> int: ...
    @property
    def recon_degraded_timeout_sec(self) -> int: ...
    @property
    def recon_uncertain_timeout_sec(self) -> int: ...


class OptimizationSettingsPort(Protocol):
    @property
    def objective_return_weight(self) -> float: ...
    @property
    def objective_sharpe_weight(self) -> float: ...
    @property
    def objective_win_rate_weight(self) -> float: ...
    @property
    def objective_drawdown_penalty(self) -> float: ...
    @property
    def objective_profit_factor_weight(self) -> float: ...
    @property
    def objective_regularization_strength(self) -> float: ...
    @property
    def objective_expectancy_weight(self) -> float: ...
    @property
    def objective_consecutive_loss_penalty(self) -> float: ...
    @property
    def objective_min_trades(self) -> int: ...
    @property
    def objective_max_drawdown_threshold(self) -> float: ...
    @property
    def objective_drawdown_cliff_penalty(self) -> float: ...
    @property
    def objective_trade_freq_weight(self) -> float: ...
    @property
    def objective_min_density_threshold(self) -> float: ...
    @property
    def objective_high_winrate_bonus(self) -> float: ...
    @property
    def objective_high_winrate_threshold(self) -> float: ...
    @property
    def objective_payoff_ratio_weight(self) -> float: ...
    @property
    def objective_payoff_ratio_cap(self) -> float: ...
    @property
    def objective_min_trades_penalty(self) -> float: ...
    @property
    def objective_min_trades_penalty_start(self) -> float: ...
    @property
    def objective_profit_factor_cap(self) -> float: ...
    @property
    def objective_consecutive_loss_threshold(self) -> int: ...
    @property
    def objective_pnl_weight(self) -> float: ...
    @property
    def objective_pnl_cap(self) -> float: ...


class ResearchSettingsPort(Protocol):
    @property
    def enabled(self) -> bool: ...
    @property
    def min_cv_sharpe(self) -> float: ...
    @property
    def max_pbo(self) -> float: ...
    @property
    def min_oos_degradation_ratio(self) -> float: ...
    @property
    def cv_folds(self) -> int: ...
    @property
    def purge_bars(self) -> int: ...
    @property
    def embargo_bars(self) -> int: ...
    @property
    def wf_train_size(self) -> int: ...
    @property
    def wf_test_size(self) -> int: ...
    @property
    def wf_expanding(self) -> bool: ...
    @property
    def wf_mode(self) -> WFMode: ...
    @property
    def min_wf_oos_sharpe(self) -> float: ...
    @property
    def wf_min_trades(self) -> int: ...
    @property
    def continuous_validation_enabled(self) -> bool: ...
    @property
    def min_continuous_trades_per_1000_bars(self) -> int: ...
    @property
    def max_continuous_drawdown_pct(self) -> float: ...
    @property
    def pbo_min_trade_returns(self) -> int: ...
    @property
    def pbo_max_partitions(self) -> int: ...
    @property
    def shock_test_enabled(self) -> bool: ...
    @property
    def shock_test_tp_shift_pct(self) -> float: ...
    @property
    def shock_test_sl_shift_pct(self) -> float: ...
    @property
    def shock_test_min_pf(self) -> float: ...
    @property
    def per_regime_pf_enabled(self) -> bool: ...
    @property
    def per_regime_min_pf(self) -> float: ...
    @property
    def per_regime_min_trades(self) -> int: ...
    @property
    def concentration_check_enabled(self) -> bool: ...
    @property
    def concentration_max_month_pct(self) -> float: ...
    @property
    def concentration_max_trade_pct(self) -> float: ...
    @property
    def pair_robustness_enabled(self) -> bool: ...
    @property
    def pair_robustness_min_pairs(self) -> int: ...
    @property
    def pair_robustness_min_pf_threshold(self) -> float: ...


class AdaptiveSettingsPort(Protocol):
    @property
    def mode(self) -> AdaptiveMode: ...


class DatabaseSettingsPort(Protocol):
    @property
    def dsn(self) -> str: ...
    @property
    def app_name(self) -> str: ...
    @property
    def connect_timeout_sec(self) -> float: ...
    @property
    def statement_timeout_ms(self) -> int: ...
    @property
    def min_connections(self) -> int: ...
    @property
    def max_connections(self) -> int: ...


class StrategyScopePort(Protocol):
    @property
    def has_strategy_rules(self) -> bool: ...
    @property
    def rules(self) -> tuple[object, ...]: ...

    def resolve(
        self,
        pair: str,
        regime: MarketState | None,
        default: StrategyParams,
        strategy: str | None = None,
    ) -> StrategyParams: ...


class RiskScopePort(Protocol):
    def resolve(self, pair: str, regime: MarketState | None, default: RiskParams) -> RiskParams: ...


# Top-level protocol


class PipelineSettings(Protocol):
    """Structural protocol matching the ``Settings`` Pydantic model.

    Application-layer code depends on this protocol.  The concrete
    ``Settings`` class in ``config.schema`` satisfies it via structural
    subtyping, verified by basedpyright at compile time.
    """

    @property
    def trading(self) -> TradingSettingsPort: ...
    @property
    def regime(self) -> RegimeSettingsPort: ...
    @property
    def strategy(self) -> StrategyParams: ...
    @property
    def risk(self) -> RiskSettingsPort: ...
    @property
    def exchange(self) -> ExchangeSettingsPort: ...
    @property
    def universe(self) -> UniverseSettingsPort: ...
    @property
    def system(self) -> SystemSettingsPort: ...
    @property
    def ai(self) -> AISettingsPort: ...
    @property
    def backtest(self) -> BacktestSettingsPort: ...
    @property
    def database(self) -> DatabaseSettingsPort: ...
    @property
    def optimization(self) -> OptimizationSettingsPort: ...
    @property
    def adaptive(self) -> AdaptiveSettingsPort: ...
    @property
    def research(self) -> ResearchSettingsPort: ...
    @property
    def flags(self) -> FlagsPort: ...
    @property
    def strategy_scope(self) -> StrategyScopePort: ...
    @property
    def risk_scope(self) -> RiskScopePort: ...
