"""Market data feed gateway protocol for real-time exchange data lifecycle."""

from typing import Protocol


class MarketDataFeedPort(Protocol):
    """Lifecycle protocol for exchange data feeds (bootstrap, stream, refresh)."""

    async def bootstrap(self) -> None: ...
    async def start(self) -> None: ...
    async def ensure_fresh(self) -> None: ...
    async def stop(self) -> None: ...
